#!/usr/bin/env python
from __future__ import division

import os
import sys
from time import time

import numpy as np
import numpy.linalg as linalg
import numpy.random as rand
import rospy
import scipy.io as io
from apriltags.msg import AprilTagDetections

import click
import deep2d
import deep2d_data
import matplotlib.pyplot as plt

# Global variables.
sim = None

def detection_callback_0(data):
    detection_callback(data, None)

def detection_callback_1(data):
    detection_callback(data, None)

def detection_callback_2(data):
    detection_callback(data, None)

def detection_callback_3(data):
    detection_callback(data, None)

def detection_callback(data, camera_pose):
    for d in data.detections:
        print d.id
        # print d.pose
    

def main():
    rospy.init_node('worldstate')
    rospy.Subscriber('/elp_cam_0/apriltags/detections', AprilTagDetections, detection_callback_0)
    rospy.Subscriber('/elp_cam_1/apriltags/detections', AprilTagDetections, detection_callback_1)
    rospy.Subscriber('/elp_cam_2/apriltags/detections', AprilTagDetections, detection_callback_2)
    rospy.Subscriber('/elp_cam_3/apriltags/detections', AprilTagDetections, detection_callback_3)
    rospy.spin()

if __name__=='__main__':
    main()
